// Maps raw scraped Vivastreet records -> the website's Profile shape,
// and emits a generated TS data module the React app imports.
//
// Run: node transform.mjs
// Output: <APP_DATA>/profiles.generated.ts  (+ a copy in ./data)

import { readFile, writeFile } from "node:fs/promises";

const APP_DATA = "/Users/burgerking/vivost/vivost/build/src/data";

const PALETTE = ["#e0f2f1", "#fce4ec", "#fff3e0", "#f3e5f5", "#e8f5e9"];

function colorFor(id) {
  let h = 0;
  for (const c of id) h = (h * 31 + c.charCodeAt(0)) >>> 0;
  return PALETTE[h % PALETTE.length];
}

function splitLocation(raw) {
  if (!raw) return { area: null, city: null };
  const p = raw.split(" - ");
  return p.length >= 2
    ? { area: p.slice(0, -1).join(" - ").trim(), city: p[p.length - 1].trim() }
    : { area: null, city: raw.trim() };
}

function categoryFor(title, services) {
  const hay = `${title || ""} ${(services || []).join(" ")}`.toLowerCase();
  if (/\bnuru\b|massage therapis|\b4 hands\b/.test(hay)) return "massage";
  return "escorts";
}

// Title minus phone numbers / dangling separators, for use as a display name.
function displayName(title) {
  if (!title) return "Untitled listing";
  let t = title
    .replace(/(?:\+?44|0)\s?7(?:[\s-]?\d){9}/g, "")
    .replace(/\s*[-–|]\s*$/g, "")
    .replace(/\s{2,}/g, " ")
    .replace(/^\s*[-–|]\s*/, "")
    .trim();
  return t || title.trim();
}

function cleanDescription(desc, title) {
  if (!desc) return "";
  let d = desc.replace(/\s+/g, " ").trim();
  // Vivastreet appends "<TITLE> escorts <area> are waiting for you..." boilerplate.
  const cut = d.search(/\bare waiting for you\b/i);
  if (cut > 40) d = d.slice(0, cut);
  // Drop a trailing repeat of the title if present.
  if (title) {
    const head = title.slice(0, 14);
    const idx = d.indexOf(head, 40);
    if (idx > 40) d = d.slice(0, idx);
  }
  return d.replace(/\s*[•|]\s*$/, "").trim();
}

function hourlyRate(rates) {
  if (!Array.isArray(rates) || rates.length === 0) return 0;
  const ph = rates.find((r) => r.unit === "p/h");
  if (ph) return ph.amount;
  return Math.min(...rates.map((r) => r.amount));
}

function availability(incall, outcall) {
  if (incall && outcall) return "Incall & Outcall";
  if (incall) return "Incall only";
  if (outcall) return "Outcall only";
  return "Available Now";
}

function buildAttributes(r) {
  const attrs = [];
  if (r.age) attrs.push({ label: "Age", value: `${r.age}` });
  if (r.gender) attrs.push({ label: "Gender", value: r.gender });
  if (r.ethnicity) attrs.push({ label: "Ethnicity", value: r.ethnicity });
  if (r.languages?.length) attrs.push({ label: "Languages", value: r.languages.join(", ") });
  if (r.ad_type) attrs.push({ label: "Type", value: r.ad_type });
  if (r.service_for) attrs.push({ label: "Available for", value: r.service_for });
  return attrs;
}

function toProfile(r) {
  const { area, city } = splitLocation(r.location_raw);
  return {
    id: r.source_ad_id,
    name: displayName(r.title),
    categorySlug: categoryFor(r.title, r.services),
    location: city || "UK",
    area: area || null,
    hourlyRate: hourlyRate(r.rates),
    availability: availability(r.incall, r.outcall),
    imageColor: colorFor(r.source_ad_id || "0"),
    photos: r.photos || [],
    description: cleanDescription(r.description, r.title) || "No description provided.",
    phone: r.phones?.[0] || null,
    age: r.age ?? null,
    gender: r.gender || null,
    ethnicity: r.ethnicity || null,
    languages: r.languages || [],
    services: r.services || [],
    verified: !!r.verified,
    hasPhone: (r.phones || []).length > 0,
    region: r.region || null,
    flags: (r.phones || []).length > 0 ? [] : ["no_phone"],
    adType: r.ad_type || null,
    serviceFor: r.service_for || null,
    sourceUrl: r.source_url,
    attributes: buildAttributes(r),
  };
}

async function main() {
  const raw = JSON.parse(
    await readFile(new URL("./data/listings.json", import.meta.url))
  );
  const profiles = raw.filter((r) => !r.error && r.source_ad_id).map(toProfile);

  const banner = `/**\n * AUTO-GENERATED by scraper/transform.mjs — do not edit by hand.\n * Source: Vivastreet escort listings. ${profiles.length} profiles.\n */\n`;
  const body =
    `import type { Profile } from './profiles';\n\n` +
    `export const PROFILES: Profile[] = ${JSON.stringify(profiles, null, 2)};\n`;
  const out = banner + body;

  await writeFile(new URL("./data/profiles.generated.ts", import.meta.url), out);
  await writeFile(`${APP_DATA}/profiles.generated.ts`, out);
  console.log(
    `Wrote ${profiles.length} profiles -> ${APP_DATA}/profiles.generated.ts (and ./data copy)`
  );
}

main();
